knpu_oauth2_client:
    clients:
        cognito:
            type: generic
            provider_class: CakeDC\OAuth2\Client\Provider\Cognito
            client_id: '%env(AWS_COGNITO_CLIENT_ID)%'
            client_secret: '%env(AWS_COGNITO_CLIENT_SECRET)%'
            redirect_route: auth_callback
            provider_options:
                cognitoDomain: '%env(OAUTH_AWS_COGNITO_DOMAIN)%'
                region: '%env(OAUTH_AWS_REGION)%'
                scope: 'openid email'
#                urlAuthorize: 'https://%env(OAUTH_AWS_COGNITO_DOMAIN)%.auth.%env(OAUTH_AWS_REGION)%.amazoncognito.com/oauth2/lgoin'
#                urlAccessToken: 'https://%env(OAUTH_AWS_COGNITO_DOMAIN)%.auth.%env(OAUTH_AWS_REGION)%.amazoncognito.com/oauth2/token'
#                urlResourceOwnerDetails: 'https://%env(OAUTH_AWS_COGNITO_DOMAIN)%.auth.%env(OAUTH_AWS_REGION)%.amazoncognito.com/oauth2/userInfo'
#        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
