version: '3.8'

services:
    php:
        build: .
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www
        environment:
            APP_ENV: test

    nginx:
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php

    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: medi_eye_auth
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
